add some extra detail to docs
Kixunil/configure_me pull request #45
Opened 2021-02-14 03:34 UTC by Shamazo

This doesn't cover all functionality, but it covers a bunch of common use cases I had to figure out to use this crate for another project. 

Question, if I use the `conf_file_param` I find that options set in that config file overwrite options set in environment variables. Is that intentional?

2021-02-14 03:40 UTC, Shamazo commented
Is the main README.md just a copy of the one in configure_me

2021-02-14 19:47 UTC, Kixunil requested changes
Thank you for contribution! I wanted to review it sooner but was unable to do so. I found some issues, even a few serious ones - those definitely need to be addressed.

> Question, if I use the `conf_file_param` I find that options set in that config file overwrite options set in environment variables. Is that intentional?

Yes, it's intentional.

2021-02-14 19:47 UTC, Kixunil commented on configure_me/README.md
> +extern crate configure_me;
This is incorrect, it must be `configure_me_codegen` in build script as mentioned above.
This particular case could be removed entirely thank to edition 2018.

2021-02-14 19:47 UTC, Kixunil commented on configure_me/README.md
> +    configure_me::build_script_auto().unwrap_or_exit();
Needs to stay `configure_me_codegen`

2021-02-14 19:47 UTC, Kixunil commented on configure_me/README.md
> -*Tip: use [`cfg_me`](https://github.com/Kixunil/cfg_me) to generate a man page for your program.*
Why was this removed? There's no way for people to generate man page without knowing about `cfg_me`.

2021-02-14 19:47 UTC, Kixunil commented on configure_me/README.md
> +configure_me_codegen = "0.3"
Damn, just realized I forgot to push the new version - `0.4` to git - it was in crates.io for a while. Pushed it now. Sorry about that.

2021-02-14 19:47 UTC, Kixunil commented on configure_me/README.md
> -    // Don't worry, unwrap_or_exit() prints a nice message instead of ugly panic
I think this should still be mentioned, maybe using different wording?

2021-02-14 19:47 UTC, Kixunil commented on configure_me/README.md
> +build = "build.rs"
Did git screw up the diff somehow? env var prefix is configured using `env_prefix`, not `build`

2021-02-14 19:47 UTC, Kixunil commented on configure_me/src/lib.rs
> +//! build = "build.rs"
Same mistake as above

2021-02-14 20:10 UTC, Shamazo commented
thanks for catching all of that, I think most of them are due to subtle differences between the documentation in the .rs and the documentation in the readme. I'll go back over it and clean things up

2021-12-15 17:22 UTC, Kixunil commented
Ping, do you intend to continue working on this?

2022-12-26 18:23 UTC, Kixunil commented
Closing due to inactivity. Feel free to open a new one when you're ready.

2022-12-26 18:23 UTC, closed without merging